Top drawer menu title
calcitem/Sanmill pull request #599
Opened 2022-10-15 08:25 UTC by mdddj

## :scroll: Description

首页侧滑抽屉菜单标题置顶

## :bulb: Motivation and Context

## :green_heart: How did you test it?

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps

2022-10-15 10:06 UTC, calcitem requested changes

2022-10-15 10:06 UTC, calcitem commented on src/ui/flutter_app/lib/shared/custom_drawer/src/widget.dart
> +  double get maxExtent => 170;
下载后在不同分辨率配置的模拟器（最小至少支持480x800）上验证，发现，maxExtent需要能够自适应才能确保各种分辨率都能正常显示标题。

2022-10-15 10:06 UTC, calcitem commented on src/ui/flutter_app/lib/shared/custom_drawer/src/widget.dart
> +  double get minExtent => 170;
可以设置成和 maxExtent 等同。

2022-10-16 03:53 UTC, mdddj commented
@calcitem 已修复
<img width="280" alt="image" src="https://user-images.githubusercontent.com/29020213/196017112-4be8dde9-7457-427b-8ca0-80a56c55a79a.png">

2022-10-16 05:38 UTC, calcitem requested changes
多谢！工作得很好。

有个瑕疵，有劳修改评论中所提到的一行。然后使用如下命令重新 Push:

```shell
git add .
git commit -m "fix"
git reset be6d3258
git checkout HEAD src/ui/flutter_app/android/app/build.gradle
git checkout HEAD src/ui/flutter_app/android/gradle/wrapper/gradle-wrapper.properties
git checkout HEAD src/ui/flutter_app/ios
git add .
git commit -m "drawer: Fix top drawer menu titile"
git push origin HEAD:master -f
```

即：本地开发环境相关的修改，如有需要，可以另做提交。

谢谢！

2022-10-16 05:38 UTC, calcitem commented on src/ui/flutter_app/lib/shared/custom_drawer/src/widget.dart
> +                  decoration: const BoxDecoration(color: Colors.white),
这行请改为：

```dart
decoration: BoxDecoration(
                      color: DB().colorSettings.drawerColor,
                    ),
```

2022-10-16 06:08 UTC, mdddj commented on src/ui/flutter_app/lib/shared/custom_drawer/src/widget.dart
> +                  decoration: const BoxDecoration(color: Colors.white),
已改

2022-10-16 06:13 UTC, calcitem approved these changes

2022-10-16 06:13 UTC, merged

2022-10-16 06:14 UTC, calcitem commented
Thanks!