Fix flutter ui
calcitem/Sanmill pull request #604
Opened 2022-10-20 13:09 UTC by xshiwei

## :scroll: Description

1. 外观设置 -> 显示语言，选择 English 上面一项，即希腊语。打开 Drawer，可以看到第2个选项 “人机对战” 对应的希腊文排列成2排，想达到的效果时，还是显示成一排，当用户点击这项后，文字如跑马灯一样从右向左滚动。或者如果能有更好的显示方式亦可，不过显示成省略号是不太合理的。进入对局，可以看到页面下方工具栏的显示异常，所有按钮都因为文字太长，而横向排列变成上下排列了。这里对于按钮下方的文字，可以考虑显示成省略号。
2. 在小屏幕手机上，打开 外观设置 -> 显示着法导航工具栏，将 “棋盘和上边缘的间距” 调到最大，返回 人机对战 界面，上下滑动页面，可以看到左上角的三个横线的导航菜单图标也跟着滑动。期望是不动，并且其位置应始终保持和设置界面中的这个图标的位置一致。
3. 点 “常规设置” -> "难度等级"，弹出的进度条不够美观，考虑改成波轮效果。

## :bulb: Motivation and Context

https://github.com/calcitem/Sanmill/issues/600

## :green_heart: How did you test it?
Tested on a minimum 768*1280 emulator

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps

2022-10-21 14:49 UTC, calcitem commented
提交 log 存在一次多余的 merge。请执行下述命令重新推送，谢谢。

```
git reset 660bafff13e0825c3c578dcdc7351da30750422b
git push origin HEAD:fix_ui -f
```

2022-10-21 15:04 UTC, calcitem commented
文字不再换行了，不过没有如跑马灯一样从右向左滚动，现在是右半侧直接不显示，玩家不知道这项代表什么意思。所以做成从右向左自动滚动才好。
工具栏的省略号已显示，OK。
波轮窗口还没有取消和确认按钮。
左上角的三个横线图标不动，修改OK。

2022-10-21 15:15 UTC, calcitem requested changes

2022-10-21 15:15 UTC, calcitem commented on src/ui/flutter_app/lib/screens/game_page/game_page.dart
> +    final itemMaxWidth = (MediaQuery.of(context).size.width - AppTheme.boardMargin * 2) / 4 - 16;
这里不知取16的原因是？

2022-10-21 15:15 UTC, calcitem commented on src/ui/flutter_app/pubspec.yaml
> +  marquee: ^2.2.3
风格是按字母序排列

2022-10-21 15:15 UTC, calcitem commented on src/ui/flutter_app/lib/shared/text_size_helper.dart
> +
多一个换行。

2022-10-21 15:15 UTC, calcitem commented on src/ui/flutter_app/lib/shared/custom_drawer/src/item.dart
> +    final isExpand = (MediaQuery.of(context).size.width * 0.75 - 44) > titleSize.width;
不知取 0.75、44 的原因？是否适合各种屏幕大小？

2022-10-21 15:15 UTC, calcitem commented on src/ui/flutter_app/lib/screens/general_settings/skill_level_picker.dart
> +            onSelectedItemChanged: (numb) {
此变量建议改为` level `。

2022-10-21 15:15 UTC, calcitem commented on src/ui/flutter_app/lib/screens/general_settings/skill_level_picker.dart
> +            itemExtent: size + 12,
感觉需要再大一些，好触摸。另外这里是乘以一个倍数更好还是加一个数更好？哪种更适合不同屏幕大小的情况？

2022-10-22 02:39 UTC, xshiwei commented on src/ui/flutter_app/lib/screens/game_page/game_page.dart
> +    final itemMaxWidth = (MediaQuery.of(context).size.width - AppTheme.boardMargin * 2) / 4 - 16;
这里是计算组件的宽度，给了一个padding。不然文字过长会连在一起。

2022-10-22 02:41 UTC, xshiwei commented on src/ui/flutter_app/lib/shared/custom_drawer/src/item.dart
> +    final isExpand = (MediaQuery.of(context).size.width * 0.75 - 44) > titleSize.width;
*0.75 计算出drawer的宽度， -44是减去Text以外的组件的宽度。这里就是计算出Text的最大宽度，超出最大宽度时改用滚动播放。 这里可能44取少了。

2022-10-22 02:43 UTC, xshiwei commented on src/ui/flutter_app/lib/screens/general_settings/skill_level_picker.dart
> +            itemExtent: size + 12,
这里其实直接设置一个固定数就行， 就可以满足不同屏幕大小情况

2022-10-22 03:27 UTC, xshiwei commented on src/ui/flutter_app/lib/screens/game_page/game_page.dart
> +    final itemMaxWidth = (MediaQuery.of(context).size.width - AppTheme.boardMargin * 2) / 4 - 16;
减去ToolbarItem内部的padding

2022-10-22 11:26 UTC, calcitem commented
难度设置波轮窗口的取消和缺点按钮分别位于左上角和右上角？这是一种设计规范惯例吗？和参考对象即 回滚步数 窗口的布局不一样。

将字体调到最大，选希腊文，Drawer 中菜单项高亮时，也没有看到跑马灯效果。

2022-10-22 11:30 UTC, calcitem requested changes

2022-10-22 11:30 UTC, calcitem commented on src/ui/flutter_app/lib/screens/general_settings/skill_level_picker.dart
> +                  )
可参考参考部分的代码，使用 `S.of(context).confirm` 以多语言化。

2022-10-22 11:30 UTC, calcitem commented on src/ui/flutter_app/lib/screens/general_settings/skill_level_picker.dart
> +                    _level = numb + 1;
貌似 number 习惯缩写是 num? 或者这里叫 value 是不是更好？

2022-10-22 11:30 UTC, calcitem commented on src/ui/flutter_app/lib/screens/general_settings/skill_level_picker.dart
> +                    child: const Text('取消'),
可参考参考部分的代码，使用 `S.of(context).cancel` 以多语言化。

2022-10-22 16:20 UTC, calcitem requested changes

2022-10-22 16:20 UTC, calcitem commented on src/ui/flutter_app/lib/shared/text_size_helper.dart
> +      {int maxLines = 2 ^ 31, double maxWidth = double.infinity}) {
理论上 `2 ^ 31` 写为 `1 << 31` 效率更高。

2022-10-22 16:34 UTC, merged